/*
  JavaScript is out of scope for this assignment.
  You should not modify anything inside this file.
*/

const movies = [
  {
    id: 1,
    name: "Shang-Chi and the Legend of the Ten Rings",
    year: 2021,
    genre: "Action, Adventure, Fantasy",
    director: "Destin Daniel Cretton",
    writer: "Dave Callaham, Destin Daniel Cretton, Andrew Lanham",
    actors: "Simu Liu, Awkwafina, Tony Chiu-Wai Leung",
    description:
      "Shang-Chi, the master of unarmed weaponry based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
    releaseDate: "03 Sep 2021",
    image: "images/shang-chi.jpeg",
    price: 2.49,
  },
  {
    id: 2,
    name: "PAW Patrol: The Movie",
    year: 2021,
    genre: "Animation, Adventure, Comedy",
    director: "Cal Brunker",
    writer: "Bob Barlen, Cal Brunker, Billy Frolick",
    actors: "Iain Armitage, Will Brisbin, Ron Pardo",
    description: "Cute dog movie",
    releaseDate: "20 Aug 2021",
    image: "images/paw-patrol.jpg",
    price: 2.99,
  },
  {
    id: 3,
    name: "Spider-Man 3",
    year: 2007,
    genre: "Action, Adventure, Sci-Fi",
    director: "Sam Raimi",
    writer: "Sam Raimi, Ivan Raimi, Alvin Sargent",
    actors: "Tobey Maguire, Kirsten Dunst, Topher Grace",
    description:
      "A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.",
    releaseDate: "04 May 2007",
    image: "images/spider-man-3.jpg",
    price: 0.5,
  },
  {
    id: 4,
    name: "Don't Breathe",
    year: 2016,
    genre: "Crime, Horror, Thriller",
    director: "Fede Alvarez",
    writer: "Fede Alvarez, Rodo Sayagues",
    actors: "Stephen Lang, Jane Levy, Dylan Minnette",
    description:
      "Hoping to walk away with a massive fortune, a trio of thieves break into the house of a blind man who isn't as helpless as he seems.",
    releaseDate: "26 Aug 2016",
    image: "images/dont-breathe.png",
    price: 1.29,
  },
  {
    id: 5,
    name: "The Dark Knight",
    year: 2008,
    genre: "Action, Crime, Drama",
    director: "Christopher Nolan",
    writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    releaseDate: "18 Jul 2008",
    image: "images/the-dark-knight.jpg",
    price: 2.99,
  },
  {
    id: 6,
    name: "The Matrix",
    year: 1999,
    genre: "Action, Sci-Fi",
    director: "Lana Wachowski, Lilly Wachowski",
    writer: "Lilly Wachowski, Lana Wachowski",
    actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    description:
      "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    releaseDate: "31 Mar 1999",
    image: "images/the-matrix.jpg",
    price: 1.79,
  },
  {
    id: 7,
    name: "Demonic",
    year: 2021,
    genre: "Horror",
    director: "Neill Blomkamp",
    writer: "Neill Blomkamp",
    actors: "Andrea Agur, Nathalie Boltt, Terry Chen",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae augue finibus, condimentum urna vel, facilisis dui. Proin est ligula, laoreet sit amet accumsan eget, aliquam ut lectus      ",
    releaseDate: "20 Aug 2021",
    image: "images/demonic.jpg",
    price: 0.49,
  },
  {
    id: 8,
    name: "The Power of the Dog",
    year: 2021,
    genre: "Drama, Romance, Western",
    director: "Jane Campion",
    writer: "Jane Campion, Thomas Savage",
    actors: "Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons",
    description:
      "Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.",
    releaseDate: "01 Dec 2021",
    image: "images/power-of-the-dog.jpg",
    price: 1.79,
  },
  {
    id: 9,
    name: "Spider-Man 2",
    year: 2004,
    genre: "Action, Adventure, Sci-Fi",
    director: "Sam Raimi",
    writer: "Stan Lee, Steve Ditko, Alfred Gough",
    actors: "Tobey Maguire, Kirsten Dunst, Alfred Molina",
    description:
      "Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Otto Octavius.",
    releaseDate: "30 Jun 2004",
    image: "images/spider-man-2.jpg",
    price: 2.49,
  },
  {
    id: 10,
    name: "Wrath of Man",
    year: 2021,
    genre: "Action, Crime, Thriller",
    director: "Guy Ritchie",
    writer: "Nicolas Boukhrief, Éric Besnard, Guy Ritchie",
    actors: "Jason Statham, Holt McCallany, Josh Hartnett",
    description: "A cold and mysterious character working at a cash truck company responsible for moving a lot of money around Los Angeles each week.",
    releaseDate: "07 May 2021",
    image: "images/wrath-of-man.jpg",
    price: 0.49,
  },
  {
    id: 11,
    name: "The Arrival of a Train",
    year: 1896,
    genre: "Action, Thriller",
    director: "Auguste Lumière, Louis Lumière",
    writer: "There ARE no writers",
    actors: "Madeleine Koehler, Jeanne-Josèphine, Mrs. Auguste Lumiere, Marcel Koehler",
    description: "Le train arrives at La Ciotat station.",
    releaseDate: "25th January 1896",
    image: "images/arrival-of-train.jpg",
    price: 2.49,
  },
  {
    id: 12,
    name: "Finding Nemo",
    year: 2003,
    genre: "Action, Adventure, Animated",
    director: "Andrew Stanton",
    writer: "Andrew Stanton, Bob Peterson, Lee Unkrich, David Reynolds",
    actors: "Andrew Stanton, Alexander Gould, Albert Brooks, Ellen DeGeneres, Wilem Dafoe",
    description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
    releaseDate: "10th October 2003",
    image: "images/finding-nemo.jpg",
    price: 1.49,
  },
  {
    id: 13,
    name: "Shrek 2",
    year: 2004,
    genre: "Adventure, Comedy, Animated",
    director: "Andrew Adamson, Kelly Asbury, Conrad Vernon",
    writer: "Andrew Adamson, Mike Myers, Kelly Asbury, Eddie Murphy",
    actors: "Andrew Adamson, Conrad Vernon, Eddie Murphy",
    description: "Shrek and Fiona travel to the Kingdom of Far Far Away, where Fiona's parents are King and Queen, to celebrate their marriage. When they arrive, they find they are not as welcome as they thought they would be.",
    releaseDate: "2nd July 2004",
    image: "images/shrek-2.jpg",
    price: 1.79,
  },
  {
    id: 14,
    name: "Interstellar",
    year: 2021,
    genre: "Action, Science Fiction, Thriller",
    director: "Christopher Nolan",
    writer: "Christopher Nolan, Jonathan Nolan",
    actors: "Matthew McConaughey, Jessica Chastain, Anne Hathaway, Mackenzie Foy, Matt Damon",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    releaseDate: "7th November 2014",
    image: "images/interstellar.jpg",
    price: 1.49,
  },
];
